# Model
model_path: "checkpoints/model/"
model_suffix: ".pth"
length_unit: "cm" 

# Root stats
root_stats_path: "checkpoints/root_stats/"
root_stats_suffix: ".npz"

# Logs
train_log_path: "results/train/"
test_log_path: "results/test/"
benchmark_log_path: "results/benchmark/"
log_suffix: ".txt"

# Benchmark parameters
benchmark_data_dir: "data/test"
benchmark_foot_joint_names: ["LeftToe", "RightToe"]
benchmark_foot_height_eps: 2.0
benchmark_foot_velocity_eps: 0.5
