length_unit: "cm" 

# Model
models_path: "checkpoints/model/"
models_suffix: ".pth"

# Root stats
root_stats_path: "checkpoints/root_stats/"
root_stats_suffix: ".npz"

# Logs
log_suffix: ".txt"
train_log_path: "results/train/"
test_log_path: "results/test/"
benchmark_log_path: "results/benchmark/"

# Testing parameters
test_data_dir: "data/test"

# Benchmark parameters
benchmark_data_dir: "data/test"
benchmark_dataset_step: 7
benchmark_dataset_batch_size: 1024
benchmark_foot_params: {
  height_eps: 2.0,
  velocity_eps: 0.5,
  joint_names: ["LeftToe", "RightToe"]
}
