# Various
length_unit: "cm" 
num_workers: 8

# Model
models_path: "checkpoints/model/"
models_suffix: ".pth"
skeletons_path: "checkpoints/skeletons/"
skeletons_suffix: ".json"

# Logs
log_suffix: ".txt"
plot_suffix: ".png"
train_log_path: "results/train/"
train_plot_path: "results/train_plots/"
test_log_path: "results/test/"
benchmark_log_path: "results/benchmark/"
