description: "same as v_17, but less root pos dropout and higher loss weights for root pos and fk pos"

# Model parameters
context_len_pre: 10
context_len_post: 10
target_len: 10
rot_gnn_params: {
  num_features: 6,
  hidden_dim: 96,
  num_layers: 7,
  dropout: 0.02,
  num_heads: 16
}
root_pos_mlp_params: {
  num_features: 3,
  hidden_dim: 256,
  num_layers: 7,
  dropout: 0.01
}
 
# Dataset parameters
step: 7                                          
batch_size: 512
num_workers: 8

# Training parameters
epochs: 200
validation_split: 0.3
patience: 7
train_data_dir: "data/train"
loss_weights: {
  rot_geo_l1: 1.0,
  root_pos_l2: 0.1,
  fk_pos_l1: 0.15
}
lr_scheduler_params: {
  start_lr: 0.001,
  min_lr: 0.000001,
  factor: 0.5,
  patience: 3
}
